"""Configuration for documentation."""
# !/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Kedro Partitioned documentation build configuration file, created by
# sphinx-quickstart on Wed Jul 27 13:25:35 2022.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
import sys
import os


sys.path.insert(0, os.path.abspath(".."))


from kedro_partitioned import __version__  # noqa: E402


extensions = [
    "sphinx.ext.autodoc",
    "autoapi.extension",
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.viewcode",
    "sphinx.ext.githubpages",
    "sphinx.ext.napoleon",
    "sphinx_autodoc_typehints",
    "sphinx_copybutton",
    "myst_parser",
    "sphinxcontrib.mermaid",
]

html_static_path = ["_static"]
html_css_files = ["style.css"]

source_suffix = ".md"

project = "Kedro Partitioned"
copyright = "2022, Ipiranga"
author = "Nickolas da Rocha Machado, Gabriel Daiha Alves"
release = __version__
language = "en"

source_suffix: list = [".md"]
templates_path = ["_templates"]
exclude_patterns: list = []
autoapi_dirs = ["../kedro_partitioned"]

html_theme = "furo"
html_static_path = ["_static"]
